import { NextPage } from "next";
import Head from "next/head";

const ProductDetail: NextPage = () => {
  return (
    <>
      <Head>
        <title>Detatlhe do produto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Detatlhe do produto</h1>
    </>
  );
};

export default ProductDetail;
