import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const ProductDetail: NextPage = () => {
  const router = useRouter();
  const productId = router.query.productId;

  return (
    <>
      <Head>
        <title>Detatlhe do produto {productId} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Detatlhe do produto {productId} </h1>
    </>
  );
};

export default ProductDetail;
