import { NextPage } from "next";
import Head from "next/head";

const Product: NextPage = () => {
  return (
    <>
      <Head>
        <title>Produtos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Produtos</h1>
    </>
  );
};

export default Product;
