import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sobre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Sobre</h1>

      <Link href="/">
        <a>Voltar</a>
      </Link>
    </>
  );
};

export default About;
